### ISSUE TITLE
Demo page is not working

### ISSUE THREAD

**Issue by mcat-ee** [ibesora/Leaflet.Quadtree#3]
Hi! I'm not sure if this is due to the API key being invalid or if the URL structure has changed, but the demo page is not working and is returning the following console errors:

![image](https://user-images.githubusercontent.com/2766980/114350937-0e804e00-9ba9-11eb-92a0-8a6b1933a6d6.png)
(the map view remains grey with no markers rendered over it)

**Comment by ibesora** [comment]
Thanks for reporting this, I'm sure the API key has expired. Will look into it and ping you back

**Comment by ibesora** [comment]
I've changed Mapbox tiles for OSM tiles and now everything is working again. 
Thanks for reporting this, and sorry for the long wait
